<?php
/**
 * Виджет вкладки "Общие сведения" (английской (британской) локализации).
 * 
 * Этот файл является частью модуля "Рабочее пространство".
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 * 
 * @var bool $empty
 * @var string profileName
 * @var string username
 * @var string visitedDate
 * @var string browser
 * @var string os
 * @var string ipAddress
 * @var string roles
 * @var array site
 */

?>
<div class="g-bs-tab__header">Common</div>
<div class="g-bs-tab__set">
<?php if ($empty) : ?>
    <div class="g-bs-tab__title">No data to display.</div>
</div>
<?php return; endif; ?>
    <div class="g-bs-tab__title">You are logged in as: <span><?= $profileName ?></span></div>
    <p><label>Authorization date:</label> <?= $visitedDate ?></p>
    <p><label>Browser:</label> <?= $browser ?></p>
    <p><label>Operating system:</label> <?= $os ?></p>
    <p><label>IP address:</label> <?= $ipAddress ?></p>
    <p><label>Username:</label> <?= $username ?></p>
    <p><label>User role:</label> <?= $roles ?></p>
    <p>&nbsp;</p>
    <div class="g-bs-tab__title">Site <span><?= GM_MULTISITE ? '(mode «Multisite»)' : '' ?></span></div>
<?php if (GM_MULTISITE && GM_MODE_DEV): ?>
    <p><label>Identifier:</label> <?= $site['id'] ?></p>
    <p><label>Data Identifier:</label> <?= $site['dataId'] ?></p>
<?php endif ?>
    <p><label>Domain:</label> <a target="_blank" href="https://<?= $site['domain'] ?>"><?= $site['domain'] ?></a></p>
    <p><label>Name:</label> <?= $site['title'] ?></p>
    <p><label>Description:</label> <?= $site['description'] ?></p>
    <p><label>Indexing:</label> <?= $site['robots'] ?: '[ not specified ]' ?></p>
    <p><label>Status:</label> <?= $site['active'] ? 'active' : 'not active' ?></p>
</div>