<?php
/**
 * Виджет вкладки "Помощь" (русской локализации).
 * 
 * Этот файл является частью модуля "Рабочее пространство".
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 * 
 * @var bool $empty
 * @var array $help
 */
?>
<div class="g-bs-tab__header">Помощь</div>
<div class="g-bs-tab__set">
<?php if ($empty) : ?>
    <div class="g-bs-tab__title">Нет данных для отображения.</div>
</div>
<?php return; endif ?>
<?php if (empty($help)) : ?>
    <div class="g-bs-tab__title">Нет разделов справки.</div>
</div>
<?php return; endif ?>
    <div class="g-bs-tab__title">Выберите один из разделов справки:</div>
    <div class="row">
        <div class="col-sm-6 col-md-4 col-lg-4">
            <div class="g-bs-thumb g-bs-thumb_icon">
                <div class="g-bs-button g-icon-svg g-icon_manual" role="widget" data-role="<?= Gm::alias('@backend', '/guide') ?>">Просмотреть</div>
                <div class="g-bs-thumb__wrap">
                    <div class="g-bs-thumb__header">Руководство пользователя</div>
                    <div class="g-bs-thumb__body">
                        <p><label>последнее обновление:</label> <?= Gm::$app->formatter->toDate(time()) ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>